//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMyPham_MVC.ServiceShopBanHang {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoreImagesField;
        
        private System.Nullable<decimal> PriceField;
        
        private System.Nullable<decimal> PromotionPriceField;
        
        private System.Nullable<bool> IncludedVATField;
        
        private System.Nullable<int> QuantityField;
        
        private System.Nullable<long> CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        private System.Nullable<int> WarrantyField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        private System.Nullable<bool> StatusField;
        
        private System.Nullable<System.DateTime> TopHotField;
        
        private System.Nullable<int> ViewField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MoreImages {
            get {
                return this.MoreImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MoreImagesField, value) != true)) {
                    this.MoreImagesField = value;
                    this.RaisePropertyChanged("MoreImages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> PromotionPrice {
            get {
                return this.PromotionPriceField;
            }
            set {
                if ((this.PromotionPriceField.Equals(value) != true)) {
                    this.PromotionPriceField = value;
                    this.RaisePropertyChanged("PromotionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<bool> IncludedVAT {
            get {
                return this.IncludedVATField;
            }
            set {
                if ((this.IncludedVATField.Equals(value) != true)) {
                    this.IncludedVATField = value;
                    this.RaisePropertyChanged("IncludedVAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<long> CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<int> Warranty {
            get {
                return this.WarrantyField;
            }
            set {
                if ((this.WarrantyField.Equals(value) != true)) {
                    this.WarrantyField = value;
                    this.RaisePropertyChanged("Warranty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<bool> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<System.DateTime> TopHot {
            get {
                return this.TopHotField;
            }
            set {
                if ((this.TopHotField.Equals(value) != true)) {
                    this.TopHotField = value;
                    this.RaisePropertyChanged("TopHot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<int> View {
            get {
                return this.ViewField;
            }
            set {
                if ((this.ViewField.Equals(value) != true)) {
                    this.ViewField = value;
                    this.RaisePropertyChanged("View");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceShopBanHang.ServiceShopBanHangSoap")]
    public interface ServiceShopBanHangSoap {
        
        // CODEGEN: Generating message contract since element name GetFeatureProductResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFeatureProduct", ReplyAction="*")]
        ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductResponse GetFeatureProduct(ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFeatureProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductResponse> GetFeatureProductAsync(ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFeatureProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFeatureProduct", Namespace="http://tempuri.org/", Order=0)]
        public ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequestBody Body;
        
        public GetFeatureProductRequest() {
        }
        
        public GetFeatureProductRequest(ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFeatureProductRequestBody {
        
        public GetFeatureProductRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFeatureProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFeatureProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductResponseBody Body;
        
        public GetFeatureProductResponse() {
        }
        
        public GetFeatureProductResponse(ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFeatureProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ShopMyPham_MVC.ServiceShopBanHang.Product[] GetFeatureProductResult;
        
        public GetFeatureProductResponseBody() {
        }
        
        public GetFeatureProductResponseBody(ShopMyPham_MVC.ServiceShopBanHang.Product[] GetFeatureProductResult) {
            this.GetFeatureProductResult = GetFeatureProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceShopBanHangSoapChannel : ShopMyPham_MVC.ServiceShopBanHang.ServiceShopBanHangSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceShopBanHangSoapClient : System.ServiceModel.ClientBase<ShopMyPham_MVC.ServiceShopBanHang.ServiceShopBanHangSoap>, ShopMyPham_MVC.ServiceShopBanHang.ServiceShopBanHangSoap {
        
        public ServiceShopBanHangSoapClient() {
        }
        
        public ServiceShopBanHangSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceShopBanHangSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceShopBanHangSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceShopBanHangSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductResponse ShopMyPham_MVC.ServiceShopBanHang.ServiceShopBanHangSoap.GetFeatureProduct(ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequest request) {
            return base.Channel.GetFeatureProduct(request);
        }
        
        public ShopMyPham_MVC.ServiceShopBanHang.Product[] GetFeatureProduct() {
            ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequest inValue = new ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequest();
            inValue.Body = new ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequestBody();
            ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductResponse retVal = ((ShopMyPham_MVC.ServiceShopBanHang.ServiceShopBanHangSoap)(this)).GetFeatureProduct(inValue);
            return retVal.Body.GetFeatureProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductResponse> ShopMyPham_MVC.ServiceShopBanHang.ServiceShopBanHangSoap.GetFeatureProductAsync(ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequest request) {
            return base.Channel.GetFeatureProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductResponse> GetFeatureProductAsync() {
            ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequest inValue = new ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequest();
            inValue.Body = new ShopMyPham_MVC.ServiceShopBanHang.GetFeatureProductRequestBody();
            return ((ShopMyPham_MVC.ServiceShopBanHang.ServiceShopBanHangSoap)(this)).GetFeatureProductAsync(inValue);
        }
    }
}
